### PR TITLE
split docker build into multistage

### PR DESCRIPTION
**Pull request by srl295**
work in progress 🚧 

- use ARG for CLDR_VERSION and CLDR_TIER (full vs modern)
- remove cldr-* from 'base' image
- add locale data as another layer

### CODE REVIEW

**Comment by srl295** [comment]
so `docker history` doesn't show the Big Win i was thinking i'd see here.

With this PR:
```
$ docker history 382dc398cfb5
IMAGE          CREATED              CREATED BY                                      SIZE      COMMENT
382dc398cfb5   36 seconds ago       |2 CLDR_TIER=modern CLDR_VERSION=39 /bin/sh …   331MB     
2bb31aefac2d   About a minute ago   /bin/sh -c #(nop)  ARG CLDR_TIER=modern         0B        
ee95e3e3fec9   About a minute ago   /bin/sh -c #(nop)  ARG CLDR_VERSION=39          0B        
bf10498c7f04   About a minute ago   /bin/sh -c #(nop) COPY dir:c46a02766a3a88235…   101MB     
f6b03f33fe6c   About a minute ago   /bin/sh -c #(nop) WORKDIR /usr/src/app          0B        
70055606aaca   5 days ago           /bin/sh -c #(nop)  CMD ["node"]                 0B        
<missing>      5 days ago           /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…   0B        
<missing>      5 days ago           /bin/sh -c #(nop) COPY file:4d192565a7220e13…   388B      
<missing>      5 days ago           /bin/sh -c apk add --no-cache --virtual .bui…   7.76MB    
<missing>      5 days ago           /bin/sh -c #(nop)  ENV YARN_VERSION=1.22.15     0B        
<missing>      5 days ago           /bin/sh -c addgroup -g 1000 node     && addu…   96.5MB    
<missing>      5 days ago           /bin/sh -c #(nop)  ENV NODE_VERSION=16.13.0     0B        
<missing>      2 months ago         /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B        
<missing>      2 months ago         /bin/sh -c #(nop) ADD file:ecdfb91a737d6c292…   5.61MB    
srl295@abeja:~/src/cldr-service [git⫢main]
```

And from DockerHub:

```
$ docker history jsahleen/cldr-service
IMAGE          CREATED        CREATED BY                                      SIZE      COMMENT
32e524cfc3ec   2 weeks ago    CMD ["yarn" "start"]                            0B        buildkit.dockerfile.v0
<missing>      2 weeks ago    EXPOSE map[3000/tcp:{}]                         0B        buildkit.dockerfile.v0
<missing>      2 weeks ago    RUN /bin/sh -c yarn # buildkit                  331MB     buildkit.dockerfile.v0
<missing>      2 weeks ago    COPY . . # buildkit                             551kB     buildkit.dockerfile.v0
<missing>      2 weeks ago    WORKDIR /usr/src/app                            0B        buildkit.dockerfile.v0
<missing>      2 weeks ago    RUN /bin/sh -c mkdir -p /usr/src/app # build…   0B        buildkit.dockerfile.v0
<missing>      2 weeks ago    /bin/sh -c #(nop)  CMD ["node"]                 0B        
<missing>      2 weeks ago    /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…   0B        
<missing>      2 weeks ago    /bin/sh -c #(nop) COPY file:238737301d473041…   116B      
<missing>      2 weeks ago    /bin/sh -c apk add --no-cache --virtual .bui…   7.63MB    
<missing>      2 weeks ago    /bin/sh -c #(nop)  ENV YARN_VERSION=1.22.15     0B        
<missing>      2 weeks ago    /bin/sh -c addgroup -g 1000 node     && addu…   104MB     
<missing>      2 weeks ago    /bin/sh -c #(nop)  ENV NODE_VERSION=14.18.1     0B        
<missing>      2 months ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B        
<missing>      2 months ago   /bin/sh -c #(nop) ADD file:9d14b111839839230…   5.62MB   
```

**Comment by srl295** [comment]
yes the overall image size is 100M higher with my change – okay

**Comment by jsahleen** [comment]
@srl295 I think the extra size may be due to using a new node image instead of the base image in the second FROM statement. Thoughts?

**Comment by jsahleen** [comment]
@srl295 Closing this as it has been dealt with.

**Pull request closed without merging**
